#!/bin/sh

xunit=$(echo "$(wattr w `lsw -r`) / 3" | bc)
yunit=$(echo "$(wattr h `lsw -r`) / 4" | bc)

focus=`pfw`
[ -n "$1" ] && { focus=$1
	shift
	chwso -r $focus
	wtf $focus
}
	
wtp $xunit $yunit $xunit $(echo "2 * $yunit" | bc) ${focus}

exec kludge "$@"