#!/bin/sh

KLDGDIR=${KLDGDIR:-/tmp}

BORDER=${BORDER:-2}
NBORDER=${DBORDER:-$BORDER}
ABORDER=${FBORDER:-$BORDER}

usage()
# TODO
{
	exit
}


iterate()
{
	next=$(echo "$2" | grep "$1" -A 1 | sed 1d)
	[ -z "$next" ] && next=$(echo "$2" | head -n 1)
	echo $next
}

test $# -lt 1 && usage
test `lsw | wc -l` -eq '1' && {
	exec kludge focus `lsw` 
	lsw > "${KLDGDIR}"/focus.wid
	exit 1 
}
pfw 2>/dev/null || exec kludge focus $(lsw | head -n 1)

case $1 in
(forward)  sort="" ;;
(backward) sort=-r ;;
esac
shift

list=$(lsw | xargs wattr yxi | sort -h $sort | awk '{ print $3 }')
target=$(pfw)
focus=$(iterate "${target}" "${list}")

exec kludge focus "$focus" 