#!/bin/sh

bord=${BORDER:-1}
abord=${ACTIVE_BORDER:-$bord}
nbord=${INACTIVE_BORDER:-$bord}

color=${BORDER_COLOR:-88cc88}
ncolor=${INACTIVE_BORDER_COLOR:-888888}

lsw $1 || exit 1

pfw >/dev/null && { #chwso -l
	chwb -s $nbord -c $ncolor `pfw`
	diff=`echo "$abord - $nbord" | bc`
	wrs $diff $diff `pfw`
	}
wtf $1
chwb -s $abord -c $color `pfw`
diff=`echo "$nbord - $abord" | bc`
wrs $diff $diff `pfw`
chwso -r `pfw`
shift

kludge "$@"