#!/bin/sh

kdir=${KLDGDIR:-/tmp}
bord=${BORDER:-3}
abord=${ACTIVE_BORDER:-$bord}
nbord=${INACTIVE_BORDER:-$bord}

color=${BORDER_COLOR:-88cc88}
ncolor=${INACTIVE_BORDER_COLOR:-222222}


test -n "$1" || exit 1
target=$1 
shift
test ! "$target" = "$(pfw 2>/dev/null)" || exit 1
wattr o "$target" && exit 1

pfw >/dev/null && { 
	pfw > "$kdir"/previous.wid
	chwso -l $(pfw)
	chwb -s $nbord -c $ncolor $(pfw)
	diff=$(echo "$abord - $nbord" | bc)
	[ ! $diff -eq 0 ] && wrs $diff $diff $(pfw)
	}
wtf $target
chwb -s $abord -c $color `pfw`
diff=`echo "$nbord - $abord" | bc`
[ ! $diff -eq 0 ] && wrs $diff $diff `pfw`
chwso -r `pfw`
pfw > ${kdir}/focus.wid

exec kludge "$@"