#!/bin/sh

# TODO: make this portable
KLUDGEDIR=/home/moth/project/kludgewm

test "$1" = '-i' && while read command; do
	exec ${KLUDGEDIR}/$command
done

test -n "$1" && exec ${KLUDGEDIR}/"${@}"
focus=""