#!/bin/sh

TMPDIR=${TMPDIR:-/tmp}

test -z $1 && echo "No enough arguments" && exit 1
test ! -e ${TMPDIR}/marks && mkdir ${TMPDIR}/marks

until test -z $1; do
	case $1 in
	 -m) shift; mark="$1"; shift ;;
	 -u) shift; rm ${TMPDIR}/marks/${1}; shift;;
	 0x*) echo $1 > ${TMPDIR}/marks/"${mark}"; shift ;;
	 --) break ;;
	 *) echo "invalid input"; shift ;;
	esac
done

kludge "$@"