#!/bin/sh
# note: none of this even works

KLDGDIR=${KLDGDIR:-/tmp}

while 	case $1 in

	(switch) nview=`lsw | xargs wattr xywhi | fgrep - | sed 's/-//'`
	oview=`lsw | xargs wattr xywhi | fgrep -v - | sed s/^/-/`
	echo "$oview" | while read window
		do	wtp $window
		done
	echo "$nview" | while read window
		do	wtp $window
		done
	;;

	(attach) mapw -m `tail -n 1 ${KLDGDIR}/hiden.wid`
	tmp=`tac ${KLDGDIR}/hiden.wid |sed 1d| tac`
	echo "$tmp" > ${KLDGDIR}/hiden.wid
	;;

	(detach) pfw >> ${KLDGDIR}/hiden.wid
	mapw -u `pfw` 
	;;

	(*) break ;;

	esac
do shift || break
done

exec kludge "$@"
# end of file
