#!/bin/sh
# watch.sh -- read window events and act on them

wew | while read event
do	case $event in
	(7:*)	kludge focus $(echo $event | cut -c 3-)	;;
	(19:*)	wattr o $(echo $event | cut -c 4-) || kludge tile ;;
	(*)	echo $event ;;
	esac
done
