#!/bin/sh

DISPLAY=:0
KLDGDIR=/tmp
BORDER=3
ACTIVE_BORDER=3
INACTIVE_BORDER=0
BORDER_COLOR=cc4444

export KLDGDIR DISPLAY TMPDIR BORDER ACTIVE_BORDER INACTIVE_BORDER BORDER_COLOR

X -quiet &
xpid=$!

sleep 2

bar & 
xmodmap .Xmodmap
hsetroot -fill ${HOME}/image/wallpaper/Stars.jpg
sxhkd 